apiVersion: v1
kind: Pod
metadata:
  labels:
    app: http-server
  name: http-server

spec:
    volumes:
    - name: shared-vol
      emptyDir: {}

    initContainers:
    - name: container-initialization
      image: busybox
      volumeMounts:
      - name: shared-vol
        mountPath: /data
      command: [ "/bin/sh", "-c" ]
      args: [ 'echo \"Website initialized successfully!\" > /data/index.html' ]

    containers:
    - image: httpd
      name: httpd
      volumeMounts:
      - name: shared-vol
        mountPath: /var/www/html/
