apiVersion: v1
kind: Pod
metadata:
  name: projected-volume-pod
spec:
  containers:
  - name: container-test
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 3600
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: kkorner-secret
          items:
            - key: password
              path: app/password
      - configMap:
          name: kkorner-configmap
          items:
            - key: key1
              path: app/config